---
title: "Prelim Analysis"
author: "Kevin Jin"
output: html_document
---

```{r}
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(rlang))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(tidyverse))



data_path <- "../data/"
file_names <- sapply(list.files(data_path), function(x){paste0(data_path, x) } )
dfs <- lapply(file_names, readr::read_delim, show_col_types = FALSE)
```

```{r}
lapply(dfs, ncol)
```

```{r}
lapply(dfs, function(x){x$ECMp |> unique() |> sort()}) 
## Air/gelatin are nothing? still missing 2....

lapply(dfs, function(x){x$Ligand |> unique() |> sort()}) 
## Ligand is important, seems like FBS is the control
```

```{r}
cols_keep <- c("WellIndex", "Well", "ArrayRow", "ArrayColumn", "ECMp", "Ligand", "MEP")
dfs[[1]][,cols_keep]
```

```{r}
col1 <- dfs[[1]] |> colnames(); #col1
col2 <- dfs[[9]] |> colnames(); #col2
col3 <- dfs[[17]] |> colnames(); #col3
stain1_cols <- col1[c(114:116, 120:123, 128:130)]
stain2_cols <- col2[c(114,115, 118:120, 126)]
stain3_cols <- col3[c(110:112)]
```



```{r}
colnames(dfs[[18]])
stain1_df <- tibble()
stain2_df <- tibble()
stain3_df <- tibble()
for(i in 1:8){
  dfs[[i]]$plate <- rep(i, nrow(dfs[[i]]))
  dfs[[i + 8]]$plate <- rep(i + 8, nrow(dfs[[i + 8]]))
  dfs[[i + 16]]$plate <- rep(i + 16, nrow(dfs[[i + 16]]))
  stain1_df <- rbind(stain1_df, dfs[[i]][,c("plate", cols_keep, 
                                            "Cells_CP_AreaShape_Area",
                                            "Cytoplasm_CP_AreaShape_Area",
                                            "Nuclei_CP_AreaShape_Area",
                                            stain1_cols)])
  stain2_df <- rbind(stain2_df, dfs[[i + 8]][,c("plate", cols_keep, 
                                                "Cells_CP_AreaShape_Area",
                                                "Cytoplasm_CP_AreaShape_Area",
                                                "Nuclei_CP_AreaShape_Area",
                                                stain2_cols)])
  stain3_df <- rbind(stain3_df, dfs[[i + 16]][,c("plate", cols_keep, 
                                                 "Nuclei_CP_AreaShape_Area",
                                                 stain3_cols)])
}
saveRDS(stain1_df, "stain1_df.rds")
saveRDS(stain2_df, "stain2_df.rds")
saveRDS(stain3_df, "stain3_df.rds")
```

```{r}
for(i in 1:length(stain1_cols)){
  var_name <- stain1_cols[i]
  png(paste0("EDA/stain_1/",var_name, ".png"), width=4, height=4, units="in", res=300)

  plot(density(stain1_df[[var_name]]), main = var_name, xlab = "val",
       y = "density")
  dev.off()
}
for(i in 1:length(stain2_cols)){
  var_name <- stain2_cols[i]
  png(paste0("EDA/stain_2/",var_name, ".png"), width=4, height=4, units="in", res=300)

  plot(density(stain2_df[[var_name]]), main = var_name, xlab = "val",
       y = "density")
  dev.off()
}
for(i in 1:length(stain3_cols)){
  var_name <- stain3_cols[i]
  png(paste0("EDA/stain_3/",var_name, ".png"), width=4, height=4, units="in", res=300)

  plot(density(stain3_df[[var_name]]), main = var_name, xlab = "val",
       y = "density")
  dev.off()
}
```

```{r}
stain1_df |> 
  group_by(plate, WellIndex, MEP) |>
  summarise(count = n(), .groups = "drop") |>
  filter(count > 15) |>
  nrow()
  
stain2_df |> 
  group_by(plate, WellIndex, MEP) |>
  summarise(count = n(), .groups = "drop") |>
  filter(count > 15)|>
  nrow()
stain3_df |> 
  group_by(plate, WellIndex, MEP) |>
  summarise(count = n(), .groups = "drop") |>
  filter(count > 15) |>
  nrow()
```

```{r}
func <- median
stain1_df |>
  group_by(MEP) |>
  summarise(
    across(all_of(stain1_cols), func),
    .groups = "drop"
  ) |> 
  mutate(ECMp = str_split(MEP, "_", simplify = TRUE)[,1],
         Ligand = str_split(MEP, "_", simplify = TRUE)[,2]) |>
  group_by(ECMp) |>
  summarise(
    across(all_of(stain1_cols), 
           ~ Ligand[which.max(.x)],
           .names = "Ligand_max_{col}")
  ) |>
  pivot_longer(cols = starts_with("Ligand_max_"), 
               names_to = "Z_column", 
               values_to = "Ligand") |>
  group_by(Ligand) |>
  summarise(count = n()) |>
  arrange(desc(count)) |>
  top_n(10, count) |>
  ggplot(aes(x = reorder(Ligand,-count) , y = count, fill = Ligand)) +
  geom_bar(stat = "identity") +
  theme_minimal() + 
  labs(
    y = "Count",
    x = "Ligand",
    title = "Top 10 Ligands In terms of Counts",
    subtitle = "Corresponding to the max value for each Stain 1 Metric for an ECMP"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")
```

```{r}
stain2_df |>
  group_by(MEP) |>
  summarise(
    across(all_of(stain2_cols), func),
    .groups = "drop"
  ) |> 
  mutate(ECMp = str_split(MEP, "_", simplify = TRUE)[,1],
         Ligand = str_split(MEP, "_", simplify = TRUE)[,2]) |>
  group_by(ECMp) |>
  summarise(
    across(all_of(stain2_cols), 
           ~ Ligand[which.max(.x)],
           .names = "Ligand_max_{col}")
  ) |>
  pivot_longer(cols = starts_with("Ligand_max_"), 
               names_to = "Z_column", 
               values_to = "Ligand") |>
  group_by(Ligand) |>
  summarise(count = n()) |>
  arrange(desc(count)) |>
  top_n(10, count) |>
  ggplot(aes(x = reorder(Ligand,-count) , y = count, fill = Ligand)) +
  geom_bar(stat = "identity") +
  theme_minimal() + 
  labs(
    y = "Count",
    x = "Ligand",
    title = "Top 10 Ligands In terms of Counts",
    subtitle = "Corresponding to the max value for each Stain 2 Metric for an ECMP"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")
```

```{r}
stain3_df |>
  group_by(MEP) |>
  summarise(
    across(all_of(stain3_cols), func),
    .groups = "drop"
  ) |> 
  mutate(ECMp = str_split(MEP, "_", simplify = TRUE)[,1],
         Ligand = str_split(MEP, "_", simplify = TRUE)[,2]) |>
  group_by(ECMp) |>
  summarise(
    across(all_of(stain3_cols), 
           ~ Ligand[which.max(.x)],
           .names = "Ligand_max_{col}")
  ) |>
  pivot_longer(cols = starts_with("Ligand_max_"), 
               names_to = "Z_column", 
               values_to = "Ligand") |>
  group_by(Ligand) |>
  summarise(count = n()) |>
  arrange(desc(count)) |>
  top_n(10, count) |>
  ggplot(aes(x = reorder(Ligand,-count) , y = count, fill = Ligand)) +
  geom_bar(stat = "identity") +
  theme_minimal() + 
  labs(
    y = "Count",
    x = "Ligand",
    title = "Top 10 Ligands In terms of Counts",
    subtitle = "Corresponding to the max value for each Stain 3 Metric for an ECMP"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")
```

```{r}
stain1_df |>
  # mutate(region = case_when(((ArrayRow <= 12) & (ArrayColumn <= 10)) ~ "top_left",
  #                           ((ArrayRow <= 23) & (ArrayColumn <= 10)) ~ "mid_left",
  #                           ((ArrayRow <= 35) & (ArrayColumn <= 10)) ~ "bot_left",
  #                           ((ArrayRow <= 12) & (ArrayColumn >= 11)) ~ "top_right",
  #                           ((ArrayRow <= 23) & (ArrayColumn >= 11)) ~ "mid_right",
  #                           ((ArrayRow <= 35) & (ArrayColumn >= 11)) ~ "bot_right",
  #                           TRUE ~ "Else")) |> 
  mutate(region = case_when(((ArrayColumn <= 10)) ~ "left",
                          ((ArrayColumn >= 11)) ~ "right",
                          TRUE ~ "Else")) |> 

  group_by(region, ECMp) |>
  summarise(
    across(all_of(stain1_cols), func),
    .groups = "drop"
  ) |> 
  group_by(ECMp) |>
  summarise(
    across(all_of(stain1_cols), 
           ~ region[which.max(.x)],
           .names = "region_max_{col}")
  ) |>
  pivot_longer(cols = starts_with("region_max_"), 
               names_to = "Z_column", 
               values_to = "region") |>
  group_by(region) |>
  summarise(count = n()) |>
  ggplot(aes(x = reorder(region,-count) , y = count, fill = region)) +
  geom_bar(stat = "identity") +
  theme_minimal() + 
  labs(
    y = "Count",
    x = "Region",
    title = "Top 10 Regions In terms of Counts",
    subtitle = "Corresponding to the max value for each Stain 1 Metric for an ECMP"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")
```

```{r}
stain1_df |>
  # mutate(region = case_when(((ArrayRow <= 12) & (ArrayColumn <= 10)) ~ "top_left",
  #                           ((ArrayRow <= 23) & (ArrayColumn <= 10)) ~ "mid_left",
  #                           ((ArrayRow <= 35) & (ArrayColumn <= 10)) ~ "bot_left",
  #                           ((ArrayRow <= 12) & (ArrayColumn >= 11)) ~ "top_right",
  #                           ((ArrayRow <= 23) & (ArrayColumn >= 11)) ~ "mid_right",
  #                           ((ArrayRow <= 35) & (ArrayColumn >= 11)) ~ "bot_right",
  #                           TRUE ~ "Else")) |> 
  mutate(region = case_when(((ArrayColumn <= 10)) ~ "left",
                          ((ArrayColumn >= 11)) ~ "right",
                          TRUE ~ "Else")) |> 

  group_by(region, ECMp) |>
  summarise(
    across(all_of(stain1_cols), func),
    .groups = "drop"
  ) |> 
  filter(Cells_CP_Intensity_MedianIntensity_CellMask >= 3500)
  ggplot(aes(x = region, y = Cells_CP_Intensity_MedianIntensity_CellMask)) +
  geom_boxplot() +
  labs(
    y = stain1_cols[1]
  )

```

```{r}
stain2_df |>
  # mutate(region = case_when(((ArrayRow <= 12) & (ArrayColumn <= 10)) ~ "top_left",
  #                           ((ArrayRow <= 23) & (ArrayColumn <= 10)) ~ "mid_left",
  #                           ((ArrayRow <= 35) & (ArrayColumn <= 10)) ~ "bot_left",
  #                           ((ArrayRow <= 12) & (ArrayColumn >= 11)) ~ "top_right",
  #                           ((ArrayRow <= 23) & (ArrayColumn >= 11)) ~ "mid_right",
  #                           ((ArrayRow <= 35) & (ArrayColumn >= 11)) ~ "bot_right",
  #                           TRUE ~ "Else")) |> 
  mutate(region = case_when(((ArrayColumn <= 10)) ~ "left",
                            ((ArrayColumn >= 11)) ~ "right",
                            TRUE ~ "Else")) |> 

  group_by(region, ECMp) |>
  summarise(
    across(all_of(stain2_cols), func),
    .groups = "drop"
  ) |> 
  group_by(ECMp) |>
  summarise(
    across(all_of(stain2_cols), 
           ~ region[which.max(.x)],
           .names = "region_max_{col}")
  ) |>
  pivot_longer(cols = starts_with("region_max_"), 
               names_to = "Z_column", 
               values_to = "region") |>
  group_by(region) |>
  summarise(count = n()) |>
  ggplot(aes(x = reorder(region,-count) , y = count, fill = region)) +
  geom_bar(stat = "identity") +
  theme_minimal() + 
  labs(
    y = "Count",
    x = "Region",
    title = "Top 10 Regions In terms of Counts",
    subtitle = "Corresponding to the max value for each Stain 2 Metric for an ECMP"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")
```

```{r}
stain3_df |>
  # mutate(region = case_when(((ArrayRow <= 12) & (ArrayColumn <= 10)) ~ "top_left",
  #                           ((ArrayRow <= 23) & (ArrayColumn <= 10)) ~ "mid_left",
  #                           ((ArrayRow <= 35) & (ArrayColumn <= 10)) ~ "bot_left",
  #                           ((ArrayRow <= 12) & (ArrayColumn >= 11)) ~ "top_right",
  #                           ((ArrayRow <= 23) & (ArrayColumn >= 11)) ~ "mid_right",
  #                           ((ArrayRow <= 35) & (ArrayColumn >= 11)) ~ "bot_right",
  #                           TRUE ~ "Else")) |> 
  # mutate(region = case_when(((ArrayRow <= 17) & (ArrayColumn <= 10)) ~ "top_left",
  #                         ((ArrayRow <= 35) & (ArrayColumn <= 10)) ~ "bot_left",
  #                         ((ArrayRow <= 17) & (ArrayColumn >= 11)) ~ "top_right",
  #                         ((ArrayRow <= 35) & (ArrayColumn >= 11)) ~ "bot_right",
  #                         TRUE ~ "Else")) |> # |> select(ArrayRow, ArrayColumn, region)
  mutate(region = case_when(((ArrayColumn <= 10)) ~ "left",
                            ((ArrayColumn >= 11)) ~ "right",
                            TRUE ~ "Else")) |> 

  group_by(region, ECMp) |>
  summarise(
    across(all_of(stain3_cols), func),
    .groups = "drop"
  ) |> 
  group_by(ECMp) |>
  summarise(
    across(all_of(stain3_cols), 
           ~ region[which.max(.x)],
           .names = "region_max_{col}")
  ) |>
  pivot_longer(cols = starts_with("region_max_"), 
               names_to = "Z_column", 
               values_to = "region") |>
  group_by(region) |>
  summarise(count = n()) |>
  ggplot(aes(x = reorder(region,-count) , y = count, fill = region)) +
  geom_bar(stat = "identity") +
  theme_minimal() + 
  labs(
    y = "Count",
    x = "Region",
    title = "Top 10 Regions In terms of Counts",
    subtitle = "Corresponding to the max value for each Stain 3 Metric for an ECMP"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")
```

```{r}
stain1_df |>
  group_by(WellIndex, ECMp) |>
  summarise(
    across(all_of(stain1_cols), func),
    .groups = "drop"
  ) |> 
  group_by(ECMp) |>
  summarise(
    across(all_of(stain1_cols), 
           ~ WellIndex[which.max(.x)],
           .names = "WellIndex_max_{col}")
  ) |>
  pivot_longer(cols = starts_with("WellIndex_max_"), 
               names_to = "Z_column", 
               values_to = "WellIndex") |>
  group_by(WellIndex) |>
  summarise(count = n()) |>
  ggplot(aes(x = reorder(WellIndex,-count) , y = count, fill = WellIndex)) +
  geom_bar(stat = "identity") +
  theme_minimal() + 
  labs(
    y = "Count",
    x = "Well Index",
    title = "Well Indicies",
    subtitle = "Corresponding to the max value for each Stain 3 Metric for an ECMP"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")

```

```{r}
stain2_df |>
  group_by(WellIndex, ECMp) |>
  summarise(
    across(all_of(stain2_cols), func),
    .groups = "drop"
  ) |> 
  group_by(ECMp) |>
  summarise(
    across(all_of(stain2_cols), 
           ~ WellIndex[which.max(.x)],
           .names = "WellIndex_max_{col}")
  ) |>
  pivot_longer(cols = starts_with("WellIndex_max_"), 
               names_to = "Z_column", 
               values_to = "WellIndex") |>
  group_by(WellIndex) |>
  summarise(count = n()) |>
  ggplot(aes(x = reorder(WellIndex,-count) , y = count, fill = WellIndex)) +
  geom_bar(stat = "identity") +
  theme_minimal() + 
  labs(
    y = "Count",
    x = "Well Index",
    title = "Well Indicies",
    subtitle = "Corresponding to the max value for each Stain 3 Metric for an ECMP"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")
```

```{r}
stain3_df |>
  group_by(WellIndex, ECMp) |>
  summarise(
    across(all_of(stain3_cols), func),
    .groups = "drop"
  ) |> 
  group_by(ECMp) |>
  summarise(
    across(all_of(stain3_cols), 
           ~ WellIndex[which.max(.x)],
           .names = "WellIndex_max_{col}")
  ) |>
  pivot_longer(cols = starts_with("WellIndex_max_"), 
               names_to = "Z_column", 
               values_to = "WellIndex") |>
  group_by(WellIndex) |>
  summarise(count = n()) |>
  ggplot(aes(x = reorder(WellIndex,-count) , y = count, fill = WellIndex)) +
  geom_bar(stat = "identity") +
  theme_minimal() + 
  labs(
    y = "Count",
    x = "Well Index",
    title = "Well Indicies",
    subtitle = "Corresponding to the max value for each Stain 3 Metric for an ECMP"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "none")
```
